services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=medsecure-docker-secret-2026
      - ML_SERVICE_URL=http://ml:8000
      - DB_PATH=./medsecure.db
    volumes:
      - backend_data:/app/uploads
      - backend_db:/app
    restart: unless-stopped

  ml:
    build: ./ml
    ports:
      - "8000:8000"
    volumes:
      - backend_db:/app/backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
  backend_db:
